model:
  enable_search: true

  arch:
    module: models.kan_denoiser
    name: KANDenoiser
    params:
      kernel_size: [3, 6, 9]

  optimizer:
    module: torch.optim
    name: AdamW
    params:
      lr: 0.001
      weight_decay: 0.001
      betas: [0.9, 0.999]

  scheduler:
    module: torch.optim.lr_scheduler
    name: CosineAnnealingLR
    params:
      T_max: 200

  loss:
    module: torch.nn
    name: MSELoss
    params: {}

  init:
    method: xavier_uniform_
    params:
      gain: 1.0
