model:
  enable_search: false
  pretrained_weights: ""

  arch:
#    module: models.mlp_denoiser
    module: models.restormer
#    module: models.mlp_denoiser_v5
#    module: models.mlp_denoiser_v4
#    module: models.mlp_denoiser_v3
#    module: models.mlp_denoiser_v2
#    module: models.mlp_denoiser_v1
#    module: models.mlp_denoiser_v0
    name: Restormer
    params:
      inp_channels: 3
      out_channels: 3
      dim: 48
      num_blocks: [4,6,6,8]
      num_refinement_blocks: 4
      heads: [1,2,4,8]
      ffn_expansion_factor: 2.66
      bias: False
      LayerNorm_type: WithBias
      dual_pixel_task: False

  optimizer:
    module: torch.optim
    name: AdamW
    params:
      lr: 0.0003
      weight_decay: 0.0001
      betas: [0.9, 0.999]

  scheduler:
    module: torch.optim.lr_scheduler
    name: CosineAnnealingLR
    params:
      T_max: 50
      eta_min: 0.000001

  loss:
    module: torch.nn
    name: MSELoss
    params: {}

  init:
    method: xavier_uniform_
    params:
      gain: 1.0
