model:
  enable_search: false

  arch:
    module: models.retinex_former
    name: Retinexformer
    params:
      {}

  optimizer:
    module: torch.optim
    name: AdamW
    params:
      lr: 0.0001
      weight_decay: 0.00001

  scheduler:
    module: torch.optim.lr_scheduler
    name: CosineAnnealingLR
    params:
      T_max: 200

  loss:
    module: models.utils.losses
    name: DenoisingDiffusionLoss
    params: {}

  init:
    method: xavier_uniform_
    params:
      gain: 1.0
