experiment:
  name: "Image Low light Enhancement"

logging:
  backend: mlflow
  project_name: "Image Low light Enhancement"
  task_name: "experiment"

#datasets: "configs/datasets/datasets.yaml"
datasets: "configs/datasets/low_light_enhancement_datasets.yaml"

training:
  device: "cuda:0"
  mode: "standard"
  seed: 42
  epochs: 50
  mixed_precision: false
  early_stopping:
    patience: 10
    min_delta: 0.001
  show_test: true

  gan:
    generator: "configs/models/unet_denoiser.yaml"
    discriminator: "configs/models/discriminator.yaml"

  standard:
#    model: "configs/models/model.yaml"
    model: "configs/models/mlp_denoiser.yaml"
#    model: "configs/models/kan_denoiser.yaml"
#    model: "configs/models/retinex_former_correction.yaml"
#    model: "configs/models/unet_denoiser.yaml"

  validation:
    module: utils.pytorch_metrics
    metrics:
      - PSNR
      - SSIM
      - GMSD
      - LPIPS
    calculate_metrics: true
    collect_outputs: true
