custom_augmentations:
  - utils.union_dataloader
  - utils.augmentation

#normalization_range: [-1, 1]
normalization_range: [0, 1]

train:
  dataloader:
    module: torch.utils.data
    name: DataLoader
    params:
      batch_size: 4
      shuffle: true
#      num_workers: 4
      pin_memory: true
#      prefetch_factor: 2
      collate_fn:
#        module: torch.utils.data._utils.collate
        module: utils.union_dataloader
        name: default_collate
  dataset:
    module: utils.union_dataloader
    name: UnionDataset
    params:
      data:
        low: [
#          "D:/Datasets/LOL-v2/Synthetic/Train/Low",
          "D:/Datasets/LOL-v2/Real_captured/Train/Low"
        ]
        target: [
#          "D:/Datasets/LOL-v2/Synthetic/Train/Normal",
          "D:/Datasets/LOL-v2/Real_captured/Train/Normal"
        ]
      patch_size: [64, 64]
      device: cpu
      transforms:
        both:
          name: ReplayCompose
          params:
            transforms:
              - name: HorizontalFlip
                params: { p: 0.5 }
              - name: VerticalFlip
                params: { p: 0.5 }
              - name: PadIfSmall
                params: { min_height: 128, min_width: 128}
              - name: RandomCrop
                params: { height: 128, width: 128 }
              - name: NormalizeImage
                params: { p: 1.0 }
              - name: ToTensorV2
                params: { }

test:
  dataloader:
    module: torch.utils.data
    name: DataLoader
    params:
      batch_size: 4
      shuffle: false
#      num_workers: 4
      pin_memory: true
#      prefetch_factor: 2
      collate_fn:
#        module: torch.utils.data._utils.collate
        module: utils.union_dataloader
        name: default_collate
  dataset:
    module: utils.union_dataloader
    name: UnionDataset
    params:
      data:
        low: [
#          "D:/Datasets/LOL-v2/Synthetic/Test/Low",
          "D:/Datasets/LOL-v2/Real_captured/Test/Low"
        ]
        target: [
#          "D:/Datasets/LOL-v2/Synthetic/Test/Normal",
          "D:/Datasets/LOL-v2/Real_captured/Test/Normal"
        ]
      patch_size: [64, 64]
      device: cpu
      transforms:
        both:
          name: ReplayCompose
          params:
            transforms:
              - name: PadIfSmall
                params: { min_height: 128, min_width: 128}
              - name: CenterCrop
                params: { height: 128, width: 128 }
              - name: NormalizeImage
                params: { p: 1.0 }
              - name: ToTensorV2
                params: { }
